[package]
name = "secrets-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
secrets-core = { path = "../secrets-core" }
secrets-local = { path = "../secrets-local" }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde.workspace = true
